set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv32)
set(triple riscv32-unknown-none-elf)
set(CMAKE_C_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_C_COMPILER_TARGET ${triple})
set(CMAKE_CXX_COMPILER /home/mccakit/dev/llvm/bin/clang++)
set(CMAKE_CXX_COMPILER_TARGET ${triple})
set(CMAKE_ASM_COMPILER /home/mccakit/dev/llvm/bin/clang)
set(CMAKE_ASM_COMPILER_TARGET ${triple})
set(CMAKE_AR /home/mccakit/dev/llvm/bin/llvm-ar)
set(CMAKE_RANLIB /home/mccakit/dev/llvm/bin/llvm-ranlib)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)

set(SDK_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../)
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_C_STANDARD 23)
set(CMAKE_C_EXTENSIONS ON)

set(CMAKE_CXX_FLAGS_INIT "--target=${triple} --sysroot=${SDK_DIR}/llvm-libc -isystem ${SDK_DIR}/libc++/include/c++/v1 -ffreestanding -O0 -fno-inline -fno-exceptions -DNDEBUG")
set(CMAKE_C_FLAGS_INIT "--target=${triple}  --sysroot=${SDK_DIR}/llvm-libc -ffreestanding -O0 -fno-inline -DNDEBUG")
set(CMAKE_ASM_FLAGS_INIT "--target=${triple}")

set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=lld -nostdlib -static --sysroot=${SDK_DIR}/llvm-libc -L${SDK_DIR}/llvm-libc/lib/riscv32-unknown-none-elf -lc -lm -L${SDK_DIR}/compiler-rt/lib/baremetal -lclang_rt.builtins-riscv32 -L${SDK_DIR}/libc++/lib -lc++abi -lc++")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT}")
